# Generated by Django 5.2.8 on 2025-11-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='ai_tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
